### PR TITLE
Fixed JSDoc comments and optional params parsing

### PR DESCRIPTION
**Pull request by 3bl3gamer**
Closes https://github.com/TypeStrong/typedoc/issues/1804 and https://github.com/TypeStrong/typedoc/issues/567

### CODE REVIEW

**Comment by pkuczynski** [comment]
Any chance to get this merged anytime soon?

**Review by ST-DDT — COMMENTED** [review]
This works very well for:

````js
 * @param {string} [name] Some optional param.
````

but not for this syntax:

````ts
 * @param [name] Some optional param.
````

as used by tsdocs/typescript.

This is caused by [consumeTypeData](https://github.com/TypeStrong/typedoc/pull/1810/files#diff-228e49910f19c44b8ed2de5981e9f30f3dd398702d47196ee5c241051f0baf33R236) that erases all leading `{}` and `[]` blocks. But if it encounters both, then the cleanup of the `{}` does not remove the separating space and thus the `[]` won't be removed. If the `[]` is the first section, then it will get removed.

Can someone enlighten me why the `[]` is removed/what is it used for originally?

**Comment by pkuczynski** [comment]
> Can someone enlighten me why the `[]` is removed/what is it used for originally in jsdocs?

Its to mark optional parameter: https://jsdoc.app/tags-param.html#optional-parameters-and-default-values

**Comment by ST-DDT** [comment]
> Its to mark optional parameter: [jsdoc.app/tags-param.html#optional-parameters-and-default-values](https://jsdoc.app/tags-param.html#optional-parameters-and-default-values)

Currently these get removed completely, so any parameter name that might be in there will be lost, before it is analyzed.
Rendering it unusable. I thought there might be a different usecase where you don't need the thing inside the `[]`.

**Comment by Gerrit0** [comment]
I believe with 0.23, this is handled by the completely reworked comment parser, thanks for the PR though!

**Pull request closed without merging**
