### PR TITLE
Add support for source links on GitHub enterprise instances

### PR DESCRIPTION
**Pull request by tomratcliffe**
This adds support for GitHub Enterprise source URLs found in the list of `git ls-remote --get-url`.

The updated regex checks for URLs like `github.acme.com` instead of just `github.com`, and then uses the matched hostname when generating the source URLs.

I didn't add any tests for this as I'm not sure what your testing strategy is/I couldn't find a testing file for just this module. Happy to try and add this in though if required!

Should be backwards compatible with old URLs.

Fixes https://github.com/TypeStrong/typedoc/issues/249, which was closed in favour of https://github.com/TypeStrong/typedoc/issues/129.

This doesn't entirely solve https://github.com/TypeStrong/typedoc/issues/129, but closes the gap on allowing GHE to work out of the box.

### CODE REVIEW

**Comment by tomratcliffe** [comment]
I had a look at writing some tests, and can get one that would test that it defaults to `github.com`, but I can't work out how to stub out the internal ShellJS module and make it return whatever I want (so I could fake having a certain remote on a git repo):

```ts
import * as github from './../lib/converter/plugins/GitHubPlugin';
import Assert = require('assert');

describe.only('GitHubRepository', function() {
    let repository = new github.Repository('', '');

    describe('Application', function() {
        describe('contructor', function() {
            it('must default to github.com hostname', function() {
                Assert.equal(repository.gitHubHostname, 'github.com');
            });
        });
    });
});
```

Any ideas @aciccarello ?

**Comment by tomratcliffe** [comment]
I figured it out, with a small refactor. Should be good to go @aciccarello!

**Comment by tomratcliffe** [comment]
@aciccarello Any thoughts on this? Thanks!

**Comment by aciccarello** [comment]
Sorry for not following up on this @tomratcliffe. I'm hoping to look at it this week.

**Comment by aciccarello** [comment]
Thanks for your contribution @tomratcliffe!

**Pull request merged**
