### PR TITLE
fix: references marked as external if path has dots

### PR DESCRIPTION
**Pull request by tsvetomir**
Closes TypeStrong/typedoc#1049

### CODE REVIEW

**Comment by tsvetomir** [comment]
The Node v6 build fails with the same error in other PRs. Should I do anything about the error here?

```diff
-<pre><code><span class="hljs-attr">export</span> = SingleExportedClass<span class="hljs-comment">;</span></code></pre>
+<pre><code><span class="hljs-attribute">export</span> = SingleExportedClass<span class="hljs-comment">;</span></code></pre>
```

**Comment by Gerrit0** [comment]
Don't worry about node 6, support has been dropped. If you merge master in, you'll see we are only testing Node 8,10,12 now.

---

I don't particularly like this solution, but looking at the rest of that function, this might be as good as it gets. I'll put this off until the weekend so that I can take a closer look. Thanks for the PR!

**Comment by tsvetomir** [comment]
I've updated the regex to ignore quotes in the path. The only assumption now is that the symbol name doesn't contain quotes.

I'm not familiar with the context here - is there a function that will get us just the path? This should be more precise than the regex.

**Comment by Gerrit0** [comment]
I suspect there probably is a way to get that information from the checker, but I don't know how off the top of my head. That's part of the reason I want to take some time to look at this more closely :)

**Comment by Gerrit0** [comment]
I spent some time looking at this today, and have come to the realization that I don't understand the reasoning behind why some `ReferenceType`s are created by the alias converter, and some are created by the reference converter.

The code hasn't really been touched since Sebastian Lenz wrote it ~4 years ago, so I'd be surprised if anyone still working on the project knows why it was done this way. I'll hopefully have the time to figure it out tomorrow.

**Comment by tsvetomir** [comment]
Okay, let me know if I can be of any help with the investigation.

**Comment by Gerrit0** [comment]
Following smart people working with TS is really helpful sometimes. I have a feeling this will be helpful in determining how this ought to work. I haven't had time to look at it yet... but I'm rather inclined to just merge this PR, it is at worst an improvement over the current behavior.

https://github.com/dsherret/ts-morph/issues/653#issuecomment-506003489

**Comment by tsvetomir** [comment]
Seems like the TS compiler drops information aliases early on — not good. The proposed hack in the issue is not relevant to Typedoc as it requires modifying the type definition.

I'm glad there is such an extensive test suite in place. I'd definitely be uncomfortable with fixing this wasn't the case.

**Comment by tsvetomir** [comment]
I'll appreciate it if this patch makes it to production, as the original issue is really getting in our way. Thanks!

**Comment by Gerrit0** [comment]
Sorry for the delay here, it's been a couple of really busy weeks.

I just tried to pull this down on a Windows machine to play with it locally before merging and ran into an issue since Windows doesn't allow quotes in file paths. I did some research and was unable to find a workaround, so I just removed that and pushed, once the build passes I'll merge.

I can't make releases, but TypeDoc is past due for one. When Anthony has the time there will be a release on the `typedoc` package. I maintain `@gerrit0/typedoc` which is just the TypeDoc master branch (+ theme master branch) if you need these changes sooner.

**Pull request merged**
