### PR TITLE
Fix theme.js in custom themes

### PR DESCRIPTION
**Pull request by cpriest**
I believe this (along with the original PR#252) fully corrects the original issue #227 as well as the regression #382.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Can you explain how this fixes the issue? In the linked PR I did, the code doing this sort of behaviour was already commented out and this change is not consistent with that commented out behaviour.

**Comment by cpriest** [comment]
Sure, I don't have much historical knowledge of the project but I believe this part of your commit:

```
+        this.addDirectory('default', Renderer.getDefaultTheme());
+        this.addDirectory('theme', theme.basePath);
```

Fixed the 'fallback' part which may not have ever been working properly.  I essentially took the other part of your commit, re-instituted the code and fixed it so that it would work properly.

**Comment by cpriest** [comment]
Shoot I did not mean for this to come into this same PR.  LMK what you'd like me to do here...

Close this one and submit them separately?  I'm not sure there is a way to pull this commit out of the PR, if you know of a way, let me know and I will.

**Comment by blakeembrey** [comment]
You can use rebase on the branch and fix it up. 

I'd also prefer that you use `const` over `let` for the PR, so feel free to also fix that up. I'd also say that class names should always use `PascalCase`, so that change might be useful. I'm not 100% on using `default` always - maybe we should check `default` before using it or use the old behaviour of `eval`?

**Comment by cpriest** [comment]
I ran the tests on my local machine and they all passed, I think Travis was running slow or something.

**Comment by cpriest** [comment]
@blakeembrey I think that may be why it was commented out as it didn't work with eval when tested against the typedoc-theme-markdown.  I based the fix on export default which is what the markdown theme had.  

If you didn't want to use the default, we could make it the same as for plugins.  The require() should pass back a function which accepts the app.  Thoughts?

I'll fix them up and re-submit.

**Comment by blakeembrey** [comment]
Sure, but we can make them both consistent by including a check like `typeof x=== 'function' ? x : x.default`. I think that'd be the best compromise to enable both use-cases for now.

Yeah, Travis sometimes has issues with the timing. Might need to increase it sometime, usually I just restart it.

**Pull request closed without merging**
