### PR TITLE
support export-declaration

### PR DESCRIPTION
**Pull request by shrinktofit**
https://github.com/TypeStrong/typedoc/issues/639

### CODE REVIEW

**Comment by aciccarello** [comment]
@shrinktofit Can you add tests to ensure we don't regress on this?

**Comment by Gerrit0** [comment]
We should evaluate this next to #801, which makes a lot more changes and may be a more complete implementation. (In particular, the changes it makes for handling renames appear to be rather important)

**Comment by carpediem-readonly** [comment]
@shrinktofit Tests are failing on your PR. Please correct and re-submit.

**Comment by gnidan** [comment]
Firstly: I published this and #1096 as NPM `@gnd/typedoc` for anyone that wants to try this out. ℹ️ 

Secondly... I noticed a problem; not sure if it's with this PR, but it seems related... the problem appears when I use this syntax along with the `--excludeNotExported` flag.
```typescript
import * as Utils from "./utils";
export { Utils };
```

Doing this, I would expect `Utils` to appear in the docs output, but it's missing, even though it's clearly exported.

Here, some screenshots to show the difference:
<details>
<summary>Without the flag, <code>Utils</code> is there</summary>
Screen Shot 2019-09-19 at 7 25 34 PM
</details>

<details>
<summary>But when you pass <code>--excludeNotExported</code>, it's missing! 😱 </summary>
Screen Shot 2019-09-19 at 7 31 13 PM
</details>

I threw up a demo repo here for anyone that's looking to reproduce: https://github.com/gnidan-finds-bugs/typedoc-pull-1079

Hope this is useful information. Let me know if there's anything I can do to help!

**Comment by gnidan** [comment]
Can this get scheduled for 0.16 as well? Not sure what the status is in relation to #801

**Comment by Gerrit0** [comment]
This should be superceded by #801

**Comment by Gerrit0** [comment]
Adding this to the 0.16 as at least one of this & #801 needs to be merged, and after spending a few hours understanding how 801 works yesterday, I want to go over this PR more carefully, I think the method used to convert modules here might be better.

**Comment by Bnaya** [comment]
hey @gnidan any chance to publish updated gnd/typedoc? :)

**Comment by Gerrit0** [comment]
#1157 has been merged, which includes support for export declarations :)

Thank you for the PR, it proved quite useful in determining how best to handle export declarations.

**Pull request closed without merging**
