### PR TITLE
chore(deps): bump typescript to 5.3.2

### PR DESCRIPTION
**Pull request by li-jia-nan**
Resolves #2445

### CODE REVIEW

**Comment by li-jia-nan** [comment]
@Gerrit0 Hi, can you review this PR ? thanks

**Comment by Gerrit0** [comment]
I definitely want a test that checks that typedoc interacts with import attributes correctly - particularly that it doesn't get confused by resolution-mode. Looks like that's the only change in this TS version that matters to typedoc

**Comment by li-jia-nan** [comment]
> I definitely want a test that checks that typedoc interacts with import attributes correctly - particularly that it doesn't get confused by resolution-mode. Looks like that's the only change in this TS version that matters to typedoc

I'm sorry, I don't know how to add a test, can you give me some tips?

**Comment by Gerrit0** [comment]
Take a look in the src/test folder - particularly the behavior.c2.test.ts file. Tests in that file use the src/test/converter2/behavior files as input, so you can set up a file which references another file that has both esm and cjs variants that export a different type, and make sure that the converted reflections also respect that. I should have time Thursday or this weekend to build tests if you don't have the time.

**Comment by Gerrit0** [comment]
Thanks!

**Comment by li-jia-nan** [comment]
> Thanks!

You're welcome, I'd like to know when is the next release ?

**Comment by Gerrit0** [comment]
Today or tomorrow, have a couple issues I'd like to get in

**Pull request merged**
