### PR TITLE
Add support for NO_COLOR environment variable

### LINKED ISSUE #1619: Add support for NO_COLOR environment variable
## Search Terms
Color escapes

## Problem
Today, TypeDoc includes ANSI colors for colorizing output. Most of the time, this is fine, but some tools don't handle it well.

## Suggested Solution
Check for NO_COLOR and don't output color codes if it is set - https://no-color.org/
tsc is adding support for NO_COLOR in an upcoming release, we should support it too.

### PR DESCRIPTION
**Pull request by krisztianb**
Closes #1619

### CODE REVIEW

**Comment by Gerrit0** [comment]
I'd like to avoid introducing new properties, instead just adding the process.env check to the logger file when creating prefixes. Introducing a new property increases the API surface with no immediate benefit that I see

**Comment by krisztianb** [comment]
Are you ok with making the property private? I think it makes sense not to query the environment variables each time a message is logged.

**Comment by Gerrit0** [comment]
Yeah, I'm good with this.

I was thinking of doing:

```ts
const messagePrefixes = "NO_COLOR" in process.env ? { ... } : { ... }
```

**Comment by happy5214** [comment]
I'm not sure if anyone will see this, but with this feature now supported, can someone add TypeDoc to the list at https://github.com/jcs/no_color? I looked there to see if TypeDoc had `NO_COLOR` support, and I ended up having to dig through the code to figure that out.

**Comment by phoneticallySAARTHaK** [comment]
@happy5214 I believe you can do that yourself? They have direction for the same 

https://github.com/jcs/no_color?tab=readme-ov-file#adding-software

**Comment by happy5214** [comment]
> @happy5214 I believe you can do that yourself? They have direction for the same
> 
> https://github.com/jcs/no_color?tab=readme-ov-file#adding-software

I considered doing it myself, but as someone who just started using TypeDoc today, I didn't want to possibly misrepresent the description or presuppose that TypeDoc's omission was a simple oversight rather than an intentional decision. I just don't know. If anything, I thought I'd ask least seek the permission of a project of which I'm not a contributor or long-time user before adding it to that list.

**Pull request merged**
