### PR TITLE
pin @types/handlebars version

### PR DESCRIPTION
**Pull request by harunurhan**
* Fixes errors caused by higher version of @types/handlebars due to
npm's auto update

Reference: https://github.com/TypeStrong/typedoc/pull/384#issuecomment-289107077

### CODE REVIEW

**Comment by aciccarello** [comment]
Thanks for the PR! I think we should pin all the `@types` dependencies since they [don't conform to semver](https://github.com/TypeStrong/typedoc/pull/384#issuecomment-289107077).

**Comment by harunurhan** [comment]
@aciccarello I agree I could also do in this PR if it's asked, I just pinned the one that I have problem with. I would appreciate if this is merged soon!

**Comment by harunurhan** [comment]
best open source project ever

**Comment by aciccarello** [comment]
@harunurhan I was hoping we'd pin all the types. Would you mind updating that?

**Comment by harunurhan** [comment]
@aciccarello done, FYI, I had to pin `@types/lodash` a bit higher due to an error with the current one.

**Pull request merged**
