### PR TITLE
Adds helper that removes double-quotes from string

### PR DESCRIPTION
**Pull request by Fleker**
In my Typedoc generation, the modules are shown in quotes
This introduces a helper that will remove quotes in my theme

### CODE REVIEW

**Comment by aciccarello** [comment]
Thanks for the PR, I hope to review soon. Note, there is a related discussion in #68

**Comment by aciccarello** [comment]
@Fleker thanks for the contribution. Is there any reason this needs to be in the typedoc helpers if it isn't used in any typedoc core?

Also, if you complete your theme, you are welcome to add it to the readme.

**Comment by Fleker** [comment]
I had scanned through the Typedoc code, although I couldn't find a way to add a Handlebar helper directly through my theme as part of a plugin. I could see how plugins are added, but I wasn't sure that I'd be able to use the same Handlebar context between my plugin and Typedoc.

**Comment by aciccarello** [comment]
See #154 [(comment)](https://github.com/TypeStrong/typedoc/issues/154#issuecomment-224483571) for how to add custom helpers to your theme. It essentially involves adding a helpers directory. Hopefully we can add some better documentation for this moving forward.

**Pull request closed without merging**
