### PR TITLE
Move sidebar to the left of content

### PR DESCRIPTION
**Pull request by futurGH**
As discussed on Discord

### CODE REVIEW

**Comment by Gerrit0** [comment]
Will be released as a part of 0.24, thanks!

**Comment by ilg-ul** [comment]
> As discussed on Discord

Is there any public discord channel? I could not find any details in the documentation.

**Comment by futurGH** [comment]
@ilg-ul Oh, I hadn't realized your issue was the one that prompted this discussion :) There's a #typedoc channel in the [TypeScript Discord server](https://discord.gg/typedoc) where design changes like this are generally discussed. It would be great to have your feedback.

**Comment by ilg-ul** [comment]
Discord does not seem happy with that link:

Screenshot 2023-03-08 at 15 39 35

**Comment by futurGH** [comment]
Whoops, that's what I get for typing faster than I'm thinking. It's https://discord.gg/typescript

**Comment by Gerrit0** [comment]
Thanks!

**Pull request merged**
