### PR TITLE
Default theme design revamp

### PR DESCRIPTION
**Pull request by futurGH**
As discussed in `#typedoc` on Discord over the past few months, the redesigned default theme is now (mostly) ready for action!
	
### Before
Old

### After
New

### CODE REVIEW

**Comment by okikio** [comment]
@futurGH How goes this?

**Comment by futurGH** [comment]
@okikio Given #1812, this PR probably won't be getting anywhere for a while.

**Comment by okikio** [comment]
Hmm....

**Comment by cspotcode** [comment]
I skimmed the code changes.  Is there anything in particular you would like review feedback on?  I plan to clone this branch locally and run it against a sample codebase, comparing the output to the old version.

I see 4 outstanding checkboxes in the issue.  Do you still want to do them as part of this PR, or do you think it's best to extract them into separate issues?

**Comment by futurGH** [comment]
I think it would be best to separate them out; the "nice to have"s aren't that difficult to implement on their own, and the code block styling should definitely be a separate issue.

**Comment by okikio** [comment]
Is there a link that can be used to preview the new default theme?

**Comment by futurGH** [comment]
Not currently; the best way to try it out is just to clone my fork, build locally, and run it on the example directory.

**Comment by futurGH** [comment]
Quick update: you can now view the example documentation rendered with the redesign at https://futurgh.github.io/typedoc/redesign - pre-redesign is also available at https://futurgh.github.io/typedoc/original for reference.

@okikio

**Comment by okikio** [comment]
@futurGH Good job, it's pretty cool

**Comment by okikio** [comment]
@futurGH I think you should have the dark mode toggle be immediately accessible, it just feels as though having is easier to reach would be better

**Pull request merged**
