### PR TITLE
Added "Readonly" flag for readonly properties

### PR DESCRIPTION
**Pull request by makana**
Readonly reflection flag for readonly properties is added.

This PR is related to #611 

The way, the abstract flag is added to the reflection is changed. It fixes the issue that abstract accessors weren't considered so far.

To extend the discusson on #611:
Does it make sense to remove the Const flag in favor of the Readonly flag?

### CODE REVIEW

**Comment by makana** [comment]
Const flag is added to const enumerations.

**Comment by aciccarello** [comment]
Thanks for the PR. This would close #585

**Comment by shlomiassaf** [comment]
@makana
TypeScript has a clear separation between `Const` and `Readonly` as so it is better that we follow their logic. When we are aligned with the language it's easier to understand the code and less chance of getting surprised.

When creating the UI it's easier as well, you want to show readonly on classes and const on variables and if they are consolidated you have to do some logic which is not optimal.

It's better to stick to the same path as TS and not create local terminology...

**Comment by makana** [comment]
@shlomiassaf 
Agreed. At least with my last commit (add const flag to enumerations) removing the const flag option is obsolete.

@aciccarello 
Since the flag is added to the "relevantFlags" array, it will be automatically rendered in the default themes.

**Comment by Gerrit0** [comment]
#1268 made these changes and has been merged in.

**Pull request closed without merging**
