### PR TITLE
Bump marked from 3.0.8 to 4.0.10

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Attempts at superseding https://github.com/TypeStrong/typedoc/pull/1844
by bumping to a more recent `@types/marked` and fixing where breaking
changes happened.

Bumps [marked](https://github.com/markedjs/marked) from 3.0.8 to 4.0.10.
- [Release notes](https://github.com/markedjs/marked/releases)
- [Changelog](https://github.com/markedjs/marked/blob/master/.releaserc.json)
- [Commits](https://github.com/markedjs/marked/compare/v3.0.8...v4.0.10)

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
Mmmh, looks like I should fix the lockfile, having a look (apologies, I'm not particularly expert in `npm`).

**Comment by stefanobaghino-da** [comment]
> Mmmh, looks like I should fix the lockfile, having a look (apologies, I'm not particularly expert in `npm`).

Fixed by https://github.com/TypeStrong/typedoc/pull/1851/commits/d959b711b2f469a93f9a2831b0edf2a2b96bdd11

**Comment by Gerrit0** [comment]
Thanks!

**Comment by stefanobaghino-da** [comment]
Many thanks for accepting the PR and immediately making a new release! 🙇🏻‍♂️

**Pull request merged**
