### PR TITLE
Upgrade typescript to v3.1.x

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request updates the TypeScript dependency to the latest stable v3.1.x version (currently v3.1.1).

### CODE REVIEW

**Comment by aciccarello** [comment]
Thanks for the contribution. We'll need to figure out why the CI failed on Node 6 before merging. ❤️

**Comment by ahocevar** [comment]
> We'll need to figure out why the CI failed on Node 6 before merging.

Not that it helps a lot, but running the tests locally on a fresh clone of master gives me the same failing tests as this branch.

**Comment by aciccarello** [comment]
There were failing tests on another PR that made a minor change so it is possible that it is a problem with the CI. I'll need to investigate but I hope to merge this this week.

**Comment by aciccarello** [comment]
Tested locally with no issues

**Comment by deltakosh** [comment]
Wonderful! Do you have an ETA for the npm update?

**Pull request merged**
