### PR TITLE
Add support for `` inside of Marked Link Brackets

### PR DESCRIPTION
**Pull request by forivall**

### CODE REVIEW

**Comment by Gerrit0** [comment]
Question, does `` `[[ link ]]` `` not work as intended? With the current behavior, the text inside brackets is taken (almost) verbatim to find symbols, and while `` ` `` isn't a very common symbol, it still introduces some complexity that it would be nice to avoid.

**Comment by forivall** [comment]
Hmm, I didn't try that because I would usually expect everything inside of
a code fence to not be interpreted.

**Comment by socsieng** [comment]
> Question, does `` `[[ link ]]` `` not work as intended? With the current behavior, the text inside brackets is taken (almost) verbatim to find symbols, and while `` ` `` isn't a very common symbol, it still introduces some complexity that it would be nice to avoid.

Using the back ticks outside of the links results in the anchor being displayed as code as opposed to the code inside the anchor tag.

My current work-around for this is:

```
[[MyClass.attribute|`MyClass.attribute`]]
```

I would obviously prefer:

```
[[`MyClass.attribute`]]
```

Any chance of this getting merged?

**Comment by Gerrit0** [comment]
I've been putting this off for a bit since I also want to update the docs surrounding linking but haven't gotten around to it. Notably, using `{@linkcode MyClass.attribute}` will also produce a link with code in the anchor tag, but isn't documented anywhere.

**Comment by Gerrit0** [comment]
Released  in 0.16.11 :)

**Pull request merged**
