### PR TITLE
✔️ name attribute added for select tag

### PR DESCRIPTION
**Pull request by Nil2000**
This PR is with reference to #2557 
Hope this resolves.

### CODE REVIEW

**Comment by Gerrit0** [comment]
This doesn't appear to solve the issue, since there isn't any `<label>` with that name for it to reference... I *think* the right approach here is to use aria-labeledby to reference the header

**Comment by Nil2000** [comment]
Hi, @Gerrit0 I introduced `<label>` and made it associated with the `name` in `<select>`. Can you verify if this is fine?

**Comment by Gerrit0** [comment]
MDN says that `<label><h3>` [is a bad idea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#headings), it looks like the theme "label-heading" ought not be a header element, and just be a label to me... which probably means the same applies to the member visibility heading... slightly more involved here than I expected!

**Comment by Nil2000** [comment]
Then it's better to use `<label>` and define a class having the same property of `<h4>`. I believe it's just the size that's require here.

**Comment by Gerrit0** [comment]
I manually merged this into the beta branch with [56f92c5](https://github.com/TypeStrong/typedoc/commit/56f92c5f2f77a7ad5da58fef13ae8602cd825762), thanks!

**Pull request closed without merging**
